# app/models/imagetype.py
"""
Base SQLModel Definition.

This module defines a `BaseSQLModel` class that serves as the foundation for
all other database models in the application. It includes common, automatically
managed fields such as `id`, `created_at`, and `updated_at`.
"""

from datetime import datetime, timezone
from typing import List, Optional, TYPE_CHECKING
from app.models.base import BaseSQLModel

from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from .image import Image

class ImageType(BaseSQLModel, table=True):
    __tablename__ = "image_type"
    """
    Represents the types of image generated by the system.

    Attributes:
        idtype (str): Key that identifies uniquely every type in the database, is built over the station alias and an autonumeric.
        name (str): Type's name, the only allowed values are: snap, timex, var.
        description (str): Description of the image type
    """
    name: str = Field(description="The name of the type")

    description: Optional[str] = Field(description="A brief description of the type")

    images: List["Image"] = Relationship(back_populates="image_type")
